name: animal4d
channels:
  - pytorch
  - nvidia
  - xformers
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy==1.26.4
  - pytorch==2.3.1
  - torchvision==0.18.1  # TODO: check which ffmpeg version to install, or disable ffmpeg install here
  - torchmetrics==1.4.0
#  - xformers==0.0.27  TODO: xformers break torch and torchvision
  - faiss-gpu==1.8.0
  - opencv==4.10.0
  - ffmpeg==4.2.2  # scenedetect may call ffmpeg in different paths (output of which ffmpeg at conda base), maybe do not install any ffmpeg and use default
  - einops==0.8.0
  - json5==0.9.6
  - timm==0.6.12
  - sentencepiece==0.2.0
  - diffusers==0.32.1
  - accelerate==1.2.1
  - matplotlib==3.9.2  # 3.6.0
  - scikit-learn==1.5.1
  - scikit-image==0.24.0
  - pandas==2.2.2
  - moviepy==1.0.3
  - configargparse==1.7
  - selenium==4.24.0  # 4.21.0
  - rclone==1.68.1
  - google-api-python-client==2.147.0
  - google-auth-httplib2==0.2.0
  - google-auth-oauthlib==0.5.2
  - pip
  - pip:  # TODO: move all to conda if possible
    - scenedetect==0.6.4
    - pytube==15.0.0
    - pytubefix==8.13.1
    - mmcv==1.3.9
    - openai==1.37.1
    - nltk==3.8.1
    - flash-attn==2.6.3
    - rclone-python==0.1.12
#    - git+https://github.com/facebookresearch/detectron2.git
    - git+https://github.com/IDEA-Research/GroundingDINO.git
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/IDEA-Research/Grounded-SAM-2.git
    - git+https://github.com/ViTAE-Transformer/ViTPose.git
    # TODO: solve conflict: detectron2 requires iopath<0.1.10, sam2 requires iopath>=0.1.10
